name: tlda
channels:
  - defaults
dependencies:
  - python=3.7.6
  - absl-py
  - pyparsing
  - pip
  - pip:
    - numpy==1.19.5
    - pillow==6.2.0
    - termcolor
    - imageio
    - imageio-ffmpeg
    - opencv-python
    - xmltodict
    - torch
    - torchvision
    - torchgeometry
    - tqdm
    - einops
    - kornia
    - glfw==1.12.0
    - opencv-python